(function () {
  let photos = [];
  let site = { title: "", tagline: "", about: "", contact: "", instagram: "" };
  let defaultCollection = "Selected Photographs";

  const photoList = document.getElementById("photoList");
  const fileInput = document.getElementById("fileInput");

  const fields = {
    title: document.getElementById("siteTitle"),
    tagline: document.getElementById("siteTagline"),
    about: document.getElementById("siteAbout"),
    contact: document.getElementById("siteContact"),
    instagram: document.getElementById("siteInstagram"),
    defaultCollection: document.getElementById("defaultCollection")
  };

  fileInput.addEventListener("change", async () => {
    const file = fileInput.files[0];
    if (!file) return;
    const text = await file.text();
    loadFromSource(text);
  });

  function loadFromSource(text) {
    // Evaluate the loaded photos.js in an isolated function scope
    // to pull out SITE, DEFAULT_COLLECTION and PHOTOS.
    try {
      const fn = new Function(text + "; return { SITE, DEFAULT_COLLECTION, PHOTOS };");
      const result = fn();
      site = Object.assign(
        { title: "", tagline: "", about: "", contact: "", instagram: "" },
        result.SITE || {}
      );
      defaultCollection = result.DEFAULT_COLLECTION || "Selected Photographs";
      photos = (result.PHOTOS || []).map(p => ({
        file: p.file || "",
        name: p.name || "",
        text: p.text || "",
        collections: (p.collections || []).join(", ")
      }));
      populateFields();
      renderPhotoList();
    } catch (err) {
      alert("Couldn't read that file. Make sure it's an unmodified photos.js.\n\n" + err.message);
    }
  }

  function populateFields() {
    fields.title.value = site.title || "";
    fields.tagline.value = site.tagline || "";
    fields.about.value = site.about || "";
    fields.contact.value = site.contact || "";
    fields.instagram.value = site.instagram || "";
    fields.defaultCollection.value = defaultCollection || "";
  }

  function renderPhotoList() {
    photoList.innerHTML = "";
    photos.forEach((photo, i) => {
      const row = document.createElement("div");
      row.className = "photo-row";
      row.innerHTML = `
        <div>
          <label>Image path</label>
          <input type="text" data-field="file" value="${escapeAttr(photo.file)}">
        </div>
        <div>
          <label>Name</label>
          <input type="text" data-field="name" value="${escapeAttr(photo.name)}">
        </div>
        <div class="full">
          <label>Caption (optional)</label>
          <input type="text" data-field="text" value="${escapeAttr(photo.text)}">
        </div>
        <div class="full">
          <label>Collections (comma-separated)</label>
          <input type="text" data-field="collections" value="${escapeAttr(photo.collections)}">
        </div>
        <div class="full row-actions">
          <span></span>
          <button class="secondary small" data-action="remove">Remove</button>
        </div>
      `;

      row.querySelectorAll("input").forEach(input => {
        input.addEventListener("input", () => {
          photos[i][input.dataset.field] = input.value;
        });
      });
      row.querySelector('[data-action="remove"]').addEventListener("click", () => {
        photos.splice(i, 1);
        renderPhotoList();
      });

      photoList.appendChild(row);
    });
  }

  document.getElementById("addPhoto").addEventListener("click", () => {
    photos.unshift({ file: "images/", name: "", text: "", collections: defaultCollection });
    renderPhotoList();
  });

  document.getElementById("generate").addEventListener("click", () => {
    document.getElementById("output").value = buildOutput();
  });

  document.getElementById("download").addEventListener("click", () => {
    const content = buildOutput();
    const blob = new Blob([content], { type: "text/javascript" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "photos.js";
    a.click();
    URL.revokeObjectURL(url);
  });

  function buildOutput() {
    const s = {
      title: fields.title.value,
      tagline: fields.tagline.value,
      about: fields.about.value,
      contact: fields.contact.value,
      instagram: fields.instagram.value
    };
    const dc = fields.defaultCollection.value;

    const photoEntries = photos.map(p => {
      const collectionsArr = p.collections
        .split(",")
        .map(c => c.trim())
        .filter(Boolean);
      return `  {
    file: ${JSON.stringify(p.file)},
    name: ${JSON.stringify(p.name)},
    text: ${JSON.stringify(p.text)},
    collections: ${JSON.stringify(collectionsArr)}
  }`;
    }).join(",\n");

    return `// Generated by admin.html
const SITE = ${JSON.stringify(s, null, 2)};

const DEFAULT_COLLECTION = ${JSON.stringify(dc)};

const PHOTOS = [
${photoEntries}
];
`;
  }

  function escapeAttr(str) {
    return String(str || "").replace(/"/g, "&quot;");
  }

  // Start with one empty row so the tool is usable without loading a file.
  renderPhotoList();
})();
