(()=>{const photos=(window.AIRSONKA_PHOTOS||[]).slice();const site=window.AIRSONKA_SITE||{};const app=document.getElementById('app');const dialog=document.getElementById('lightbox');const lbImg=document.getElementById('lightboxImage');const lbInfo=document.getElementById('lightboxInfo');let currentList=[];let currentIndex=0;const byNewest=a=>b=>b.sourceOrder-a.sourceOrder;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const slug=s=>String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function metaLine(p){return [p.location,p.year].filter(Boolean).map(esc).join(' · ')}
function visualDistance(a,b){const A=a.visual||{},B=b.visual||{};const dh=Math.min(Math.abs((A.h||0)-(B.h||0)),1-Math.abs((A.h||0)-(B.h||0)));return 1.6*dh+1.05*Math.abs((A.v||0)-(B.v||0))+.75*Math.abs((A.s||0)-(B.s||0))+.55*Math.abs((A.c||0)-(B.c||0))}
function randomPick(arr){return arr[Math.floor(Math.random()*arr.length)]}
function coherentSelection(list,count){if(list.length<=count)return list.slice().sort(()=>Math.random()-.5);const anchor=randomPick(list);let scored=list.filter(p=>p.id!==anchor.id).map(p=>({p,d:visualDistance(anchor,p)})).sort((a,b)=>a.d-b.d);const close=scored.slice(0,Math.max(count*4,30));const far=scored.slice(Math.floor(scored.length*.55));const chosen=[anchor];const used=new Set([anchor.id]);while(chosen.length<count){const contrast=Math.random()<(site.contrastShare??.18);let pool=(contrast?far:close).filter(x=>!used.has(x.p.id));if(!pool.length)pool=scored.filter(x=>!used.has(x.p.id));if(!pool.length)break;let item;if(contrast){item=randomPick(pool.slice(0,Math.max(8,Math.ceil(pool.length*.5))))}else{const limit=Math.min(pool.length,Math.max(8,count*2));const i=Math.floor(Math.pow(Math.random(),2)*limit);item=pool[i]}chosen.push(item.p);used.add(item.p.id)}return chosen}
function coherentAround(anchor,list,count){if(!list.length||count<=0)return [];const scored=list.filter(p=>p.id!==anchor.id).map(p=>({p,d:visualDistance(anchor,p)})).sort((a,b)=>a.d-b.d);const close=scored.slice(0,Math.max(count*5,35));const far=scored.slice(Math.floor(scored.length*.62));const chosen=[];const used=new Set();while(chosen.length<count&&used.size<scored.length){const contrast=Math.random()<(site.contrastShare??.12);let pool=(contrast?far:close).filter(x=>!used.has(x.p.id));if(!pool.length)pool=scored.filter(x=>!used.has(x.p.id));if(!pool.length)break;const limit=Math.min(pool.length,Math.max(10,count*3));const item=contrast?randomPick(pool.slice(0,limit)):pool[Math.floor(Math.pow(Math.random(),2.2)*limit)];chosen.push(item.p);used.add(item.p.id)}return chosen}
function portraitChoice(anchor,list){let candidates=list.filter(p=>p.id!==anchor.id);const regular=candidates.filter(p=>(p.aspect||1)>.55&&(p.aspect||1)<2.05);if(regular.length)candidates=regular;const scored=candidates.map(p=>({p,d:visualDistance(anchor,p)})).sort((a,b)=>a.d-b.d);return scored.length?randomPick(scored.slice(0,Math.min(16,scored.length))).p:null}
function heroFirst(set){if(!set.length)return set;let landscape=set.filter(p=>p.aspect>1.18);if(!landscape.length)return set;let pool=landscape.slice().sort((a,b)=>b.aspect-a.aspect);let pick=randomPick(pool.slice(0,Math.min(10,pool.length)));return [pick,...set.filter(p=>p.id!==pick.id)]}
function shuffle(arr){const a=arr.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function setActive(route){document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.dataset.route===route))}
function titleHover(p){return p.title?`<span class="photo-title-hover">${esc(p.title)}</span>`:''}
function heroCopy(){const t=String(site.heroTitle||'Photos for a softer world.').trim();return t?`<div class="home-hero-copy">${esc(t).replace(/\n/g,'<br>')}</div>`:''}
function stripPhoto(p){return `<article class="selected-strip-card" data-photo="${esc(p.id)}"><img loading="lazy" src="${esc(p.thumb)}" alt="${esc(p.title||'AirSonka photograph')}">${titleHover(p)}</article>`}
function portraitPhoto(p){return `<article class="selected-strip-portrait" data-photo="${esc(p.id)}"><img loading="lazy" src="${esc(p.thumb)}" alt="${esc(p.title||'AirSonka photograph')}">${titleHover(p)}</article>`}
function wirePhotos(list){currentList=list;document.querySelectorAll('[data-photo]').forEach(el=>el.addEventListener('click',()=>{const id=el.dataset.photo;const i=currentList.findIndex(p=>p.id===id);openLightbox(i<0?0:i)}))}
function randomCollections(count=4){const cs=collections();return shuffle(cs).slice(0,Math.min(count,cs.length))}
function collectionCover(list){const sorted=list.slice().sort((a,b)=>b.sourceOrder-a.sourceOrder);const candidates=sorted.filter(p=>p.aspect>.8);return randomPick(candidates.length?candidates:sorted)}
function renderSelected(){setActive('selected');const sel=photos.filter(p=>p.selected).sort((a,b)=>b.sourceOrder-a.sourceOrder);if(!sel.length){app.innerHTML=`<section class="page"><div class="page-head"><div><p class="eyebrow">AirSonka</p><h1 class="page-title">Selected</h1></div></div><p class="empty">No photographs are marked as Selected yet. Open <b>editor.html</b> to curate the landing page.</p></section>`;return}
const heroCandidates=sel.filter(p=>p.aspect>1.18);const hero=randomPick(heroCandidates.length?heroCandidates:sel);const portrait=portraitChoice(hero,sel);const remaining=sel.filter(p=>p.id!==hero.id&&(!portrait||p.id!==portrait.id));let landscapeRemaining=remaining.filter(p=>(p.aspect||1)>=1.15&&(p.aspect||1)<=2.0);if(landscapeRemaining.length<6)landscapeRemaining=remaining.filter(p=>(p.aspect||1)>1.05);if(landscapeRemaining.length<6)landscapeRemaining=remaining;const companions=coherentAround(portrait||hero,landscapeRemaining,6);const strip=[...(portrait?[portrait]:[]),...companions];const set=[hero,...strip];const homeCollections=randomCollections(4);
app.innerHTML=`<section class="home-page">
  <div class="home-hero-shell">
    <article class="home-hero" data-photo="${esc(hero.id)}"><img src="${esc(hero.src)}" alt="${esc(hero.title||'AirSonka photograph')}">${titleHover(hero)}</article>
  </div>
  <section class="home-selected-band" aria-label="Selected photographs">
    <div class="home-band-head"><h1>${esc(site.homeLabel||'Selected')}</h1><a class="text-link" href="#all">View all photographs</a></div>
    <div class="selected-strip">
      ${portrait?portraitPhoto(portrait):''}
      <div class="selected-strip-right">
        <div class="selected-strip-row selected-strip-row-top">${companions.slice(0,3).map(stripPhoto).join('')}</div>
        <div class="selected-strip-row selected-strip-row-bottom">${companions.slice(3,7).map(stripPhoto).join('')}</div>
      </div>
    </div>
  </section>
  <section class="home-collections">
    <div class="home-section-head"><h2>COLLECTIONS</h2><a class="text-link" href="#collections">View all collections</a></div>
    ${homeCollections.length?`<div class="home-collection-grid">${homeCollections.map(([name,list])=>{const cover=collectionCover(list);return `<a class="home-collection-card" href="#collection/${encodeURIComponent(name)}"><div class="home-collection-image"><img loading="lazy" src="${esc(cover.thumb)}" alt="${esc(name)}"></div><div class="home-collection-label"><span>${esc(name)}</span></div></a>`}).join('')}</div>`:`<p class="empty home-empty">No collections are assigned yet. Add collection names in <b>editor.html</b>. Once you have them, four random collections will appear here automatically.</p>`}
  </section>
</section>`;wirePhotos(set)}
function browseCard(p){const meta=metaLine(p);return `<article class="browse-card" data-photo="${esc(p.id)}"><img loading="lazy" src="${esc(p.thumb)}" alt="${esc(p.title||'AirSonka photograph')}">${p.title?`<div class="browse-title">${esc(p.title)}</div>`:'<div class="browse-title"></div>'}${meta?`<div class="browse-meta">${meta}</div>`:''}</article>`}
function renderAll(){setActive('all');const list=photos.slice().sort((a,b)=>b.sourceOrder-a.sourceOrder);app.innerHTML=`<section class="page"><div class="page-head"><div><p class="eyebrow">Archive</p><h1 class="page-title">All Photos</h1></div><p class="page-note">Newest files first. Titles appear below when available.</p></div><div class="browse-grid">${list.map(browseCard).join('')}</div></section>`;wirePhotos(list)}
function collections(){const m=new Map();photos.forEach(p=>(p.collections||[]).forEach(c=>{const key=c.trim();if(!key)return;if(!m.has(key))m.set(key,[]);m.get(key).push(p)}));return [...m.entries()].sort((a,b)=>a[0].localeCompare(b[0]))}
function renderCollections(){setActive('collections');const cs=collections();app.innerHTML=`<section class="page"><div class="page-head"><div><p class="eyebrow">Themes</p><h1 class="page-title">Collections</h1></div><p class="page-note">Theme collections can overlap. A photograph may belong to more than one.</p></div>${cs.length?`<div class="collection-grid">${cs.map(([name,list])=>{const sorted=list.slice().sort((a,b)=>b.sourceOrder-a.sourceOrder);const cover=sorted.find(p=>p.aspect>1)||sorted[0];return `<a class="collection-card" href="#collection/${encodeURIComponent(name)}"><div class="collection-cover"><img loading="lazy" src="${esc(cover.thumb)}" alt="${esc(name)}"></div><div class="collection-name"><h2>${esc(name)}</h2><span>${list.length} photographs</span></div></a>`}).join('')}</div>`:`<p class="empty">Collections are ready technically, but none are assigned yet. Add names such as “Sea”, “Architecture” or your own themes in <b>editor.html</b>. They will appear here automatically.</p>`}</section>`}
function renderCollection(name){setActive('collections');const found=collections().find(([n])=>n===name);if(!found){location.hash='#collections';return}const list=found[1].slice().sort((a,b)=>b.sourceOrder-a.sourceOrder);app.innerHTML=`<section class="page"><div class="page-head"><div><p class="eyebrow"><a class="text-link" href="#collections">Collections</a></p><h1 class="page-title collection-page-title">${esc(name)}</h1></div><p class="page-note">${list.length} photographs, newest first.</p></div><div class="browse-grid">${list.map(browseCard).join('')}</div></section>`;wirePhotos(list)}
function renderAbout(){setActive('about');const paras=(site.aboutParagraphs||[]).filter(Boolean);app.innerHTML=`<section class="page"><div class="page-head"><div><p class="eyebrow">AirSonka</p><h1 class="page-title">${esc(site.aboutTitle||'About')}</h1></div></div><div class="prose">${paras.map(p=>`<p>${esc(p)}</p>`).join('')}</div></section>`}
function renderContact(){setActive('contact');const links=[];if(site.email)links.push(`<a href="mailto:${esc(site.email)}">${esc(site.email)}</a>`);if(site.instagram)links.push(`<a target="_blank" rel="noopener" href="${esc(site.instagram)}">Instagram</a>`);if(site.flickr)links.push(`<a target="_blank" rel="noopener" href="${esc(site.flickr)}">Flickr</a>`);app.innerHTML=`<section class="page"><div class="page-head"><div><p class="eyebrow">AirSonka</p><h1 class="page-title">${esc(site.contactTitle||'Contact')}</h1></div></div><div class="prose"><p>${esc(site.contactIntro||'')}</p></div>${links.length?`<div class="contact-links">${links.join('')}</div>`:`<p class="empty">Contact details can be added in <b>editor.html</b> whenever you are ready.</p>`}</section>`}
function detailHTML(p){const meta=metaLine(p);const cols=(p.collections||[]).filter(Boolean);return `${p.title?`<h2 class="detail-title">${esc(p.title)}</h2>`:''}${meta?`<div class="detail-meta">${meta}</div>`:''}${p.description?`<div class="detail-description">${esc(p.description)}</div>`:''}${cols.length?`<div class="detail-collections">${cols.map(c=>`<a href="#collection/${encodeURIComponent(c)}" onclick="document.getElementById('lightbox').close()">${esc(c)}</a>`).join('')}</div>`:''}`}
function syncLightboxInfoTop(){if(!dialog.open)return;if(window.innerWidth<=1050){lbInfo.style.paddingTop='';return}const r=lbImg.getBoundingClientRect();lbInfo.style.paddingTop=Math.max(0,Math.round(r.top))+'px'}
function openLightbox(i){if(!currentList.length)return;currentIndex=(i+currentList.length)%currentList.length;const p=currentList[currentIndex];lbImg.onload=()=>requestAnimationFrame(syncLightboxInfoTop);lbImg.src=p.src;lbImg.alt=p.title||'AirSonka photograph';lbInfo.innerHTML=detailHTML(p);lbInfo.scrollTop=0;if(!dialog.open)dialog.showModal();document.body.classList.add('no-scroll');requestAnimationFrame(()=>requestAnimationFrame(syncLightboxInfoTop))}
function step(n){openLightbox(currentIndex+n)}
window.addEventListener('resize',()=>{if(dialog.open)requestAnimationFrame(syncLightboxInfoTop)});document.querySelector('.lightbox-close').addEventListener('click',()=>dialog.close());document.querySelector('.lightbox-prev').addEventListener('click',()=>step(-1));document.querySelector('.lightbox-next').addEventListener('click',()=>step(1));dialog.addEventListener('close',()=>document.body.classList.remove('no-scroll'));dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});document.addEventListener('keydown',e=>{if(!dialog.open)return;if(e.key==='ArrowLeft')step(-1);if(e.key==='ArrowRight')step(1)});
const nav=document.querySelector('.nav');document.querySelector('.menu-toggle').addEventListener('click',()=>nav.classList.toggle('open'));nav.addEventListener('click',()=>nav.classList.remove('open'));
function route(){const raw=decodeURIComponent(location.hash.replace(/^#/,'')||'selected');if(raw==='selected')renderSelected();else if(raw==='all')renderAll();else if(raw==='collections')renderCollections();else if(raw.startsWith('collection/'))renderCollection(raw.slice(11));else if(raw==='about')renderAbout();else if(raw==='contact')renderContact();else renderSelected();window.scrollTo(0,0)}
window.addEventListener('hashchange',route);document.getElementById('footerText').textContent=site.footer||'© AirSonka';const brandTagline=document.getElementById('brandTagline');if(brandTagline){const t=String(site.heroTitle||'').trim();brandTagline.textContent=t;brandTagline.hidden=!t}route();})();